apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-ci-demo
  labels:
    app: devops-ci-demo
spec:
  selector:
    matchLabels:
      app: devops-ci-demo
  replicas: 1
  template:
    metadata:
      name: devops-ci-demo
      labels:
        app: devops-ci-demo
    spec:
      containers:
        - name: devops-demo-container  # Updated container name
          image: backend/dockerdemo:latest  # Updated Docker image
          imagePullPolicy: Never
          ports:
            - containerPort: 8383
---
apiVersion: v1
kind: Service
metadata:
  name: devops-ci-demo
  labels:
    app: devops-ci-demo
spec:
  type: NodePort
  selector:
    app: devops-ci-demo
  ports:
    - name: http
      port: 8383
      targetPort: 8383
